name: cinemore
description: An application that uses TMDb to show the best of movies


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.11.1+8
  cloud_firestore: ^0.12.7
  shared_preferences: ^0.5.3+2
  cached_network_image: 2.0.0-rc
  http: 0.12.0+2
  json_annotation: ^2.0.0
  intl: ^0.16.0
  sqflite:
  path_provider:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/background.png


